### ISSUE TITLE
Knockout Phase timedate Issue

### ISSUE THREAD

**Issue by nSpider** [estiens/world_cup_json#100]
The datetime value of the matches of knockout phase is not correct. Please fix

**Comment by estiens** [comment]
Yup, working on it in the new scrapers. For some reason it pulls in the bracket HTML and not the list view with the timedates. Working on clicking the link in the scraper and waiting for the new HTML to appear.

**Comment by estiens** [comment]
I believe all these are fixed now with the new scrapers!

**Comment by FelipeCCSacramento** [comment]
Hi, 

the datetime of group stage matches are in local time, I don't know if its the same problem.

**Comment by estiens** [comment]
yes, just deployed another timezone fix that went wrong because FIFA actually has the wrong UTC time set as an attribute of their matches -- if UTC is after before||equal to 12 it is correct, but if UTC is say 3:00 PM on that day, they use 03:00 in the UTC string instead of 15:00 so it comes 12 hours early...

**Comment by estiens** [comment]
ok, i have a hacky workaround in place for the FIFA bug, should be correct now I believe unless a game is early in the morning. Will try to spot check them all and fix manually if I have time.

**Comment by nSpider** [comment]
Thank you  guys for this update.... love you.
