### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by estiens** [estiens/world_cup_json#106]
I increased the throttling to a maximum of 3 requests every 30 seconds.

You /really/ shouldn't have to poll more often than this as we aren't scraping that quickly. If you have a specific need for me let me know and I can whitelist your IP. If you are running some sort of app, please don't make a separate API call every time a user interaction! I'm open to adjusting this to find the sweet spot, but 1 request every 10s seems pretty quick (and throttles fully half of the current requests)

However, this change is better for everyone with the smarter caching as well. Much less server load and decreased the 95th percentile response time from about 500ms to 50ms.

**Comment by cedricblondeau** [comment]
Hi @estiens 

Thanks for making this great API public. That's really appreciated.

It seems that the throttling strategy that is running in prod right now is limiting to 1 request every 10s instead of 3 requests every 30 seconds.

As a result, it's not possible anymore to fetch the current game info and today matches at the same time for instance. Which is probably something you may want to do if you build a web app or a dashboard.

Any chance we can make this 3 requests every 30 seconds instead of 1 request every 10s, so an app can fire 2 API calls on start?

**Comment by estiens** [comment]
Are you still having this problem? I can request 3 in a row within 1 second
no problem. I did set it up so multiple calls could be made. Load seems
really stable now, so I’ll probably start increasing this over time.


On June 19, 2018 at 7:39:45 PM, Cédric Blondeau (notifications@github.com)
wrote:

Hi @estiens <https://github.com/estiens>

Thanks for making this great API public. That's really appreciated.

It seems that the throttling strategy that is running in prod right now is
limiting to 1 request every 10s instead of 3 requests every 30 seconds.

As a result, it's not possible anymore to fetch the current game info and
today matches at the same time for instance. Which is probably something
you may want to do if you build a web app or a dashboard.

Any chance we can make this 3 requests every 30 seconds instead of 1
request every 10s, so an app can fire 2 API calls on start?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/estiens/world_cup_json/issues/106#issuecomment-398588090>,
or mute the thread

**Comment by pedsm** [comment]
Has the limit has been decided? If so I think this could be added on the README on a Rate limiting subsection

**Comment by estiens** [comment]
Good idea! Added!
