### ISSUE TITLE
Saudi Arabia Egypt match wrong result

### ISSUE THREAD

**Issue by PhilipWoulfe** [estiens/world_cup_json#127]
Looks like Saudi Arabia vs Egypt is listing as 1 - 1 when it should be 2 - 1 to Saudi Arabia?

**Comment by kbzone** [comment]
api: https://worldcup.sfg.io/matches

the final score was:
Saudi Arabia (2) Egypt (1)

the api shows: 1 - 1

but in the "home_team_events" shows the goal: 
{
"id": 616,
"type_of_event": "goal",
"player": "SALEM ALDAWSARI",
"time": "90'+5'"
}

tip: the second goal of Arabia was made after 90'

remember to fix this api too:
https://worldcup.sfg.io/teams/results

to both teams (arabia and egypt)

**Comment by estiens** [comment]
believe this will fix itself shortly with an automatic double check (looks like fixed now, both score and events) -- team results automatically updates when matches change no worry there. Score should always be picked up correctly, event might get added in next sweep, in this case I think it was because other match ended so the score classes changed again, but fix for that should be in as well now so all should be well going forward.

**Comment by PhilipWoulfe** [comment]
Looks to have resolved itself.

**Comment by kbzone** [comment]
great, thanks for all your awesome work @estiens 😊
