### ISSUE TITLE
401 Unauthorized while running  clock: bundle exec clockwork lib/new_scraper_clock.rb on Dokku

### ISSUE THREAD

**Issue by ttpro1995** [estiens/world_cup_json#135]
I setup Dokku on Digital Ocean
(commit f6741b04a27ac54a84ee7470dcc72a23fe90020a) 
check log, I see

```
2018-06-26T08:21:57.036382605Z app[clock.1]: E, [2018-06-26T08:21:57.036175 #8] ERROR -- : Expected([200, 201, 202, 204, 206, 304]) <=> Actual(401 Unauthorized)
2018-06-26T08:21:57.036423213Z app[clock.1]:  (Excon::Error::Unauthorized)

```

more logs https://gist.github.com/ttpro1995/e9ee83a4b9344bb15bd68dcad6f3078c

**Comment by simofacc** [comment]
@ttpro1995 This happens because of the new gem scout_apm. Just remove that from the Gemfile and run `bundle install` before pushing. It should fix the issue. If you check line 7 of your log file you will see that it's just missing the configuration, so unless you want to use that service just remove the gem.
