### ISSUE TITLE
France v Argentina – Still marked as "in progress" after full time.

### ISSUE THREAD

**Issue by nolaneo** [estiens/world_cup_json#150]
As much as I'd love that game to go on for longer 😄, the API is still returning "in progress" after the match has been finished for some time now.

I wonder did FIFA change something with their site for the knockout stages that it's not seeing FT anymore?

**Comment by estiens** [comment]
Nope, my fault on that one. Put in guard logic to make sure matches could never be marked draws in the knockout rounds, but set draw to nil instead of false on match completion and that database column can't ever be nil, only true or false, so the match couldn't save it's completed state after the match ended. will push up a fix now and should resolve itself.

**Comment by nolaneo** [comment]
Legend! It looks good now 🙂
Thanks!
