### ISSUE TITLE
Missing CORS headers

### ISSUE THREAD

**Issue by andyewen** [estiens/world_cup_json#198]
It looks like the API responses are missing the `Access-Control-Allow-Origin: *` header which means I can't access the API from the browser. I noticed that this header was previously included. Was it deliberately removed?

I can set up a proxy server if necessary but it would be handy to be able to talk to the API directly.

**Comment by estiens** [comment]
I mean you certainly CAN access the API from anywhere - for instance here's a browser a curl request from a terminal - there is nothing on /this/ side that says you can't do this or you shouldn't do this - but i don't need to have a debate about headers and HTTP semantics, can put those in no worries if it will help make using JS libraries easier

<img width="649" alt="Screenshot 2022-11-19 at 1 15 11 AM" src="https://user-images.githubusercontent.com/4022668/202839572-4fd02293-1525-4ede-ba2c-767b0809ea10.png">

<img width="814" alt="Screenshot 2022-11-19 at 1 14 33 AM" src="https://user-images.githubusercontent.com/4022668/202839575-263ba851-c3e6-4fb7-932f-3acc64c2a6ab.png">

**Comment by estiens** [comment]
Let me know if it works for you now, added access-control-origin * (but since it has literally no authentication or cares about where you you are accessing it from, as long as the way you ingest the data doesn't care where it gets it, you shouldn't have any probs)

That being said a ton of libraries throw misleading CORS errors if they don't get a response so if that's the case let me know!

**Comment by zacharylr** [comment]
I had the same problem and it looked like the fix was working yesterday but the problem came back today for me.

I can't access the API from the browser as it throws CORS erroré

Thanks!

**Comment by estiens** [comment]
Should be fixed now! Was having some throttling issues, let me know if still an issue thanks!
