### ISSUE TITLE
2018 World cup ?

### ISSUE THREAD

**Issue by CyrilNb** [estiens/world_cup_json#50]
Hi dude, 

I'm wondering if your API will provide data for the upcoming 2018 world cup (men) this summer ?
And if so, is there any release date ?

I would love to use it for a little project in Swift :D
Thanks man !

**Comment by estiens** [comment]
I would like to get the API running, but unfortunately it depends on scraping real-time data from the FIFA website. If the website has changed, which seems likely, the scraper will not work. I am currently looking into any other APIs that might be available for the world cup this time around, if there are no easily accessible/free ones, I will probably try to make this one work again, but it likely won't work until after the tournament has started, as I will need to adjust the scraper to make sure I am getting all match stats in there.

**Comment by sw-tracker** [comment]
Hi, I'm also looking into APIs. Have you found any good free ones?
Thanks!

**Comment by CyrilNb** [comment]
Hey! Unfortunately I didn't yet..
estiens, any news from your side ?
Thanks !

**Comment by sw-tracker** [comment]
I found one that seems to be working pretty well:
http://api.football-data.org
I hope this helps!

**Comment by CyrilNb** [comment]
Great find ! Thx dude ! Have fun programming then :)

**Comment by estiens** [comment]
I've updated the code to work for 2018. Should be ready for the start of games tomorrow for real time results. It might take a day or two to get substitutions and cards and goal scorers to work because FIFA has changed their HTML structure. I was able to figure out the general match data structure, but live events will be determined after a few of them take place.

**Comment by CyrilNb** [comment]
Thanks for the update man by taking in consideration our request!
Really appreciate, I'm gonna use your API :)

**Comment by jinnks** [comment]
The live match has already started but the end point shows that it starts at 17:00, is that because of a different timezone?
http://worldcup.sfg.io/matches/today shows no results

**Comment by estiens** [comment]
Sorry, the scraper wasn't quite tuned correctly yet because of the changes to the HTML structure. Live scoring should be working now, and real time goal scorers, cards, and subs will be pushed up this afternoon for the games tomorrow. It's always a bit of a trial and error process at the beginning to figure out the exact HTML structure FIFA is using to report, and this time they are using a lot of show/hide stuff with JS as well.

**Comment by jinnks** [comment]
I understand thanks
