### ISSUE TITLE
2018 World cup ?

### ISSUE THREAD

**Issue by joaowillamy** [estiens/world_cup_json#51]
2018 World cup ?

**Comment by estiens** [comment]
Check the README :)

**Comment by estiens** [comment]
I've updated the code to work for 2018. Should be ready for the start of games tomorrow for real time results. It might take a day or two to get substitutions and cards and goal scorers to work because FIFA has changed their HTML structure. I was able to figure out the general match data structure, but live events will be determined after a few of them take place.
