### ISSUE TITLE
Do you have a filter for men vs women in your api!?

### ISSUE THREAD

**Issue by famictech2000** [estiens/world_cup_json#52]
Im using your sample links on the site and it brings back the women schedule and scores. Is there anyway to limit it to either men or women ?

**Comment by estiens** [comment]
It was originally set up for the Men's World Cup in 2014, then altered to support the Women's World Cup in 2016. It is not known whether it will work for 2018 or not, as likely the site structure has changed. 

People are encouraged to seek out alternate APIs or wait and see whether this one will work. As it is a scraper, we won't be able to test until after scores and games go live and make alterations then.

**Comment by estiens** [comment]
I've updated the code to work for 2018. Should be ready for the start of games tomorrow for real time results. It might take a day or two to get substitutions and cards and goal scorers to work because FIFA has changed their HTML structure. I was able to figure out the general match data structure, but live events will be determined after a few of them take place.
