### ISSUE TITLE
score not updating

### ISSUE THREAD

**Issue by arussellsaw** [estiens/world_cup_json#54]
bruh
![screen shot 2018-06-14 at 16 42 06](https://user-images.githubusercontent.com/5236823/41422924-e6a8580e-6ff1-11e8-8220-5debaa6df1cc.png)

**Comment by adambuckland** [comment]
`http://worldcup.sfg.io/matches/current`

sadly gives:
```
[]
```

**Comment by estiens** [comment]
Sorry, the scraper wasn't quite tuned correctly yet because of the changes to the HTML structure. Live scoring should be working now, and real time goal scorers, cards, and subs will be pushed up this afternoon for the games tomorrow. It's always a bit of a trial and error process at the beginning to figure out the exact HTML structure FIFA is using to report, and this time they are using a lot of show/hide stuff with JS as well.

**Comment by arussellsaw** [comment]
thanks dude!
