### ISSUE TITLE
updated every minute not working

### ISSUE THREAD

**Issue by Angelk90** [estiens/world_cup_json#78]
@estiens : 
Hi, congratulations on the project.

I was giving a look, but it seems that the minute-by-minute update does not seem to work in current, today, matches.

**Comment by dg01d** [comment]
Yes, I noticed that its not working since the second half of the Peru-Denmark game.

**Comment by Angelk90** [comment]
@dg01d : In fact it remained 0-0.

**Comment by mickzer** [comment]
@Angelk90 no it didn't: https://www.fifa.com/worldcup/matches/match/300331528/#match-liveblog

**Comment by Angelk90** [comment]
@mickzer: See here: http://worldcup.sfg.io/
in TODAY'S MATCHES
The result is still 0-0

I know that the match is not over 0-0, but 0-1

**Comment by Rickycezar** [comment]
During the match, the server was responding with an error code 500. Probably something happened during the match and the live feed stopped being updated.

**Comment by Shajeel-Afzal** [comment]
@Rickycezar through which language are you parsing the FIFA website? If it is Node.js then please deploy on Firebase Cloud Functions. It will give you 100% up time and cost is very low.

**Comment by Shajeel-Afzal** [comment]
Oh, I see that it is ROR Project.

**Comment by christophfriedrich** [comment]
@Rickycezar Concerning the 500 code: FIFA's infrastructure seems to be a little unreliable, e.g. yesterday it took them dozens of minutes until final results appeared on the website. So it wouldn't surprise me if the system screwed up mid-game...

@Shajeel-Afzal In the future, please have a brief look at the repo before asking basic questions. And then ask the question in its own thread - hijacking a random issue to start forum chatter is not good practice.

**Comment by Angelk90** [comment]
@christophfriedrich : So the problem that still the result between Peru-Denmark has not been updated could be caused FIFA's infrastructure?

**Comment by christophfriedrich** [comment]
I doubt that, because the result is fine on their website. Also, I didn't have any look at this repo's code, so don't put too much expectation into my comments. But if @Rickycezar observed 500s during the game, that may have broken the continuous updating of the rails app (just guessing) and maybe it just didn't start again? I'd suggest to keep calm and wait for @estiens's response to this issue.

**Comment by Rickycezar** [comment]
@christophfriedrich Yes, I took a look on how the project scrapes the site and the way FIFA's site behave is nightmarish. I'm using this api to get game data, but i'm also working on alternatives, because the source for this one is not reliable enough. This API does an amazing job, but you can never trust FIFA's feed if it stays as it is now.

**Comment by Angelk90** [comment]
@christophfriedrich , @Rickycezar : I think something happened as you can see in:
http://worldcup.sfg.io/matches/current
Still it remains that you are playing peru-denmark.

**Comment by Legoburner73** [comment]
I observed a failure on the peru-denmark score counter on tv. That thing runs on FIFA's Infrastructure so it seems like that failed and is still broke

**Comment by Legoburner73** [comment]
It seems like the system has fixed itself!

**Comment by Angelk90** [comment]
@Legoburner73 : now it seems that the situation has been released, but according to the bees Denmark has not scored.

**Comment by estiens** [comment]
Hi all, sorry for the delay --

We were under sustained DDoS attack since right after the Argentina match this morning. In taking mitigation steps, I accidentally broke the JS functionality of the scraper. DDoS attack (and future ones) are now mitigated with a variety of steps including a throttler (please don't make requests every second!). Scraper is now back to normal and all should be good.

Sorry for delay in response, was AFK (or I would have known I broke the scraper). Also have a monitor on that job now to catch errors.

All should be well going forward.

**Comment by psalaberria002** [comment]
The result of the last match is wrong. Denmark won 0 - 1

**Comment by Angelk90** [comment]
@psalaberria002 : it seems that the problem has been solved.

@estiens :
Do not worry, in fact you did a great job. ;)
I allowed myself to open the question in case nobody noticed it.

**Comment by estiens** [comment]
Thanks for opening it!
